### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by SamTebbs33**

### CODE REVIEW

**Comment by xieyuheng** [comment]
thank you Sam :)

**Comment by SamTebbs33** [comment]
You're welcome! :)

**Comment by xieyuheng** [comment]
@SamTebbs33 
do you konw lily ?

**Comment by SamTebbs33** [comment]
I don't actually

**Comment by xieyuheng** [comment]
@SamTebbs33 
I wonder how do you find this repo :)

**Comment by SamTebbs33** [comment]
Oh someone that I follow starred it, which I saw so I thought I'd check the repo out :)

**Pull request merged**
